## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Check for and remove missing values in 'Department' and 'Attrition'
df_cleaned = attrition_df.dropna(subset=['Department', 'Attrition'])
df_cleaned.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [4]:
# Create y_df with the Attrition and Department columns
y_df = df_cleaned[['Attrition', 'Department']]
y_df.head()



Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [5]:
# Create a list of at least 10 column names to use as X data
selected_columns = ['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime', 'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']


# Create X_df using your selected columns
X_df = df_cleaned[selected_columns]

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [6]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)




In [7]:
print(X_df.columns)

Index(['Education', 'Age', 'DistanceFromHome', 'JobSatisfaction', 'OverTime',
       'StockOptionLevel', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsSinceLastPromotion', 'NumCompaniesWorked'],
      dtype='object')


In [8]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
# OneHotEncoder / fit / reshape
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

X_train['OverTime'] = label_encoder.fit_transform(X_train['OverTime'])
X_train.head()
X_test["OverTime"] = label_encoder.fit_transform(X_test["OverTime"])
X_test.head()






Education  Age  DistanceFromHome  JobSatisfaction  OverTime  \
1041          3   28                 5                1         0   
184           2   53                13                1         0   
1222          1   24                22                3         0   
67            3   45                 7                1         0   
220           2   36                 5                2         0   

      StockOptionLevel  WorkLifeBalance  YearsAtCompany  \
1041                 0                3               5   
184                  2                3               4   
1222                 1                3               1   
67                   1                3               1   
220                  0                4              13   

      YearsSinceLastPromotion  NumCompaniesWorked  
1041                        1                   0  
184                         1                   1  
1222                        0                   1  
67                          0                   2  
220                         3                   8

In [9]:
print(X_test.shape)
print(y_test.shape)

(294, 10)
(294, 2)


In [10]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)


# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)



In [11]:
# Trim X_train_scaled
#X_train_scaled = X_train_scaled[:1176]

In [12]:
'''print("X_train_scaled shape:", X_train_scaled.shape)
print("y_train_enc_department shape:", y_train_enc_department.shape)
print("y_train_enc_attrition shape:", y_train_enc_attrition.shape)'''

'print("X_train_scaled shape:", X_train_scaled.shape)\nprint("y_train_enc_department shape:", y_train_enc_department.shape)\nprint("y_train_enc_attrition shape:", y_train_enc_attrition.shape)'

In [13]:
print(X_train.shape)
print(y_train.shape)

(1176, 10)
(1176, 2)


In [14]:

# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder
department_encoder = OneHotEncoder(sparse_output=False)




# Fit the encoder to the training data
department_encoder.fit(np.array(y_train['Department']).reshape(-1, 1))

# Create two new variables by applying the encoder to the training and testing data
y_train_enc_department = department_encoder.transform(np.array(y_train['Department']).reshape(-1, 1))
y_test_enc_department = department_encoder.transform(np.array(y_test['Department']).reshape(-1, 1))




# Display results
print("Training Data Encoded Department:")
print(y_train_enc_department[:5])
print("Testing Data Encoded Department:")
print(y_test_enc_department.shape)









Training Data Encoded Department:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]]
Testing Data Encoded Department:
(294, 3)


In [15]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(drop=None, handle_unknown='ignore', sparse_output=False)

# Fit the encoder to the training data
attrition_encoder.fit(np.array(y_train['Attrition']).reshape(-1, 1))

# Create two new variables by applying the encoder to the training and testing data
y_train_enc_attrition = attrition_encoder.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_test_enc_attrition = attrition_encoder.transform(np.array(y_test['Attrition']).reshape(-1, 1))

# Display
print("Training Data Encoded Attrition:")
print(y_train_enc_attrition[:5])
print("Testing Data Encoded Attrition:")
print(y_test_enc_attrition.shape)





Training Data Encoded Attrition:
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
Testing Data Encoded Attrition:
(294, 2)


## Create, Compile, and Train the Model

In [16]:
y_train_enc_department
#y_train_enc_attrition

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
# Find the number of columns in the X training data
number_input_features = len(X_train_scaled[0])
number_input_features




# Create the input layer
input = layers.Input(shape=(number_input_features,), name='input')


# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu',name='shared_layer1')(input)
shared_layer2 = layers.Dense(units=32, activation='relu',name='shared_layer2')(shared_layer1)


In [18]:
print(X_train_scaled.shape)

(1176, 10)


In [19]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
department_hidden = layers.Dense(units=32, activation='relu',name='department_hidden')(shared_layer2)


# Create the output layer
#department_output = layers.Dense(units=3, activation='softmax',)(department_hidden)
department_output = layers.Dense(y_train_enc_department.shape[1], activation='sigmoid', name='department_output')(department_hidden)
# maybe softmax




In [20]:
# Create a branch for Attrition
# with a hidden layer and an output layer
# Create the hidden layer
attrition_hidden = layers.Dense(units=32, activation='relu',name='attrition_hidden')(shared_layer2)




# Create the output layer
#output_attrition = layers.Dense(units=2, activation='softmax')(hidden_layer)
#attrition_output = layers.Dense(units=2, activation='softmax',)(attrition_hidden)
attrition_output = layers.Dense(y_train_enc_attrition.shape[1], activation='sigmoid', name='attrition_output')(attrition_hidden)





In [21]:
# Create the model
model = Model(inputs=input, outputs=
              [{'department_output':department_output, 'attrition_output': attrition_output}])



# Compile the model
#model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.compile(
    optimizer='adam',
    loss={
        'department_output': 'categorical_crossentropy',
        'attrition_output': 'categorical_crossentropy'
    },
    metrics={
        'department_output': 'accuracy',
        'attrition_output': 'accuracy'
    }
)
# Summarize the model
model.summary()


Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input (InputLayer)        │ (None, 10)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer1 (Dense)     │ (None, 64)             │            704 │ input[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ shared_layer2 (Dense)     │ (None, 32)             │          2,080 │ shared_layer1[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_hidden (Dense)  │ (None, 32)             │          1,056 │ shared_layer2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_hidden (Dense) │ (None, 32)             │          1,056 │ shared_layer2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │             66 │ attrition_hidden[0][0] │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │             99 │ department_hidden[0][… │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 5,061 (19.77 KB)

 Trainable params: 5,061 (19.77 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# Train the model
fit_model = model.fit(X_train_scaled, [{'department_output':y_train_enc_department,'attrition_output':y_train_enc_attrition}], epochs=100)
print(fit_model.history)

#fit_model = model.fit(X_train_scaled, [{'department_output':y_department_train, 'attrition_output':y_attrition_train}], epochs=100)




Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - attrition_output_accuracy: 0.5074 - attrition_output_loss: 0.6881 - department_output_accuracy: 0.5796 - department_output_loss: 0.9625 - loss: 1.6507
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8395 - attrition_output_loss: 0.4338 - department_output_accuracy: 0.6763 - department_output_loss: 0.7745 - loss: 1.2083
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8328 - attrition_output_loss: 0.3974 - department_output_accuracy: 0.6586 - department_output_loss: 0.7743 - loss: 1.1716
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_accuracy: 0.8515 - attrition_output_loss: 0.3666 - department_output_accuracy: 0.6440 - department_output_loss: 0.7960 - loss: 1.1626
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8469 - attrition_output_loss: 0.3725 - department_output_accuracy: 0.6532 - department_output_loss: 0.

In [26]:
# Evaluate the model with the testing data
#model_loss, model_accuracy = model.evaluate(X_test_scaled, [{'department_output':y_test_enc_department, 'attrition_output':y_test_enc_attrition}])

#model_loss, model_accuracy = model.evaluate(X_train_scaled, [y_test_enc_department, y_test_enc_attrition], verbose=2)
#print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

# Evaluate the model with the testing data
eval_result = model.evaluate(X_test_scaled, [{'department_output':y_test_enc_department, 'attrition_output':y_test_enc_attrition}], verbose=2)
# Display accurac

print(eval_result)

10/10 - 0s - 6ms/step - attrition_output_accuracy: 0.8265 - attrition_output_loss: 1.1279 - department_output_accuracy: 0.4932 - department_output_loss: 1.6201 - loss: 2.7301
[2.730067014694214, 1.1279133558273315, 1.620120644569397, 0.8265306353569031, 0.4931972920894623]


In [28]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {eval_result[4]}")
print(f"Attrition Accuracy: {eval_result[3]}")



Department Accuracy: 0.4931972920894623
Attrition Accuracy: 0.8265306353569031


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy did not seem to be the best of the metrics for this dataset, especially for the department classification task, given the low accuracy score. It’s likely that the data has class imbalances or complexities that accuracy alone cannot capture. Metrics like precision, recall, F1-score, or a confusion matrix would give more insight into the model’s performance, particularly for minority classes.
2. I used softmax for both output layers because it is ideal for multi-classification tasks like predicting departmens. Softmax provides a normalized probability distribution, allowing the model to assign confidence scores to each class.  This makes it well suited for categorical outputs.
3. Hyperparameter tuning and Feature Engineering.